### ISSUE TITLE
Dataset verification in dev environment

### ISSUE THREAD

**Issue by vinnyinverso** [ESIPFed/ubd-tool-remotedb#68]
```2021-05-07T14:26:34.659-04:00 | Traceback (most recent call last):
-- | --
  | 2021-05-07T14:26:34.659-04:00 | File "/var/task/flask/app.py", line 2447, in wsgi_app
  | 2021-05-07T14:26:34.659-04:00 | response = self.full_dispatch_request()
  | 2021-05-07T14:26:34.659-04:00 | File "/var/task/flask/app.py", line 1952, in full_dispatch_request
  | 2021-05-07T14:26:34.659-04:00 | rv = self.handle_user_exception(e)
  | 2021-05-07T14:26:34.659-04:00 | File "/var/task/flask/app.py", line 1821, in handle_user_exception
  | 2021-05-07T14:26:34.659-04:00 | reraise(exc_type, exc_value, tb)
  | 2021-05-07T14:26:34.659-04:00 | File "/var/task/flask/_compat.py", line 39, in reraise
  | 2021-05-07T14:26:34.659-04:00 | raise value
  | 2021-05-07T14:26:34.659-04:00 | File "/var/task/flask/app.py", line 1950, in full_dispatch_request
  | 2021-05-07T14:26:34.659-04:00 | rv = self.dispatch_request()
  | 2021-05-07T14:26:34.659-04:00 | File "/var/task/flask/app.py", line 1936, in dispatch_request
  | 2021-05-07T14:26:34.659-04:00 | return self.view_functions[rule.endpoint](**req.view_args)
  | 2021-05-07T14:26:34.659-04:00 | File "/var/task/app.py", line 472, in verify_dataset
  | 2021-05-07T14:26:34.659-04:00 | g.verify_relationship(app_name, doi, session['orcid'])
  **| 2021-05-07T14:26:34.659-04:00 | File "/var/task/util/graph_db.py", line 330, in verify_relationship
  | 2021-05-07T14:26:34.659-04:00 | .property('verifier', verifier).next()**
  | 2021-05-07T14:26:34.659-04:00 | File "/var/task/gremlin_python/process/traversal.py", line 89, in next
  | 2021-05-07T14:26:34.659-04:00 | return self.__next__()
  | 2021-05-07T14:26:34.659-04:00 | File "/var/task/gremlin_python/process/traversal.py", line 50, in __next__
  | 2021-05-07T14:26:34.659-04:00 | self.last_traverser = next(self.traversers)
  | 2021-05-07T14:26:34.659-04:00 | StopIteration

```

**Comment by vinnyinverso** [comment]
Related to encoding difference in switch from hardcoded url to url_for.
